# Generated by Django 4.0.6 on 2022-07-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_usersubmittedanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usersubmittedanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usersubmittedanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='UserSubmittedAnswer',
        ),
    ]
