# Generated by Django 4.0.6 on 2022-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_answer_category_question_quizzes_delete_todo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
