# Generated by Django 4.0.6 on 2022-07-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_question_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
