# Generated by Django 4.0.6 on 2022-07-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='finished_time',
            field=models.IntegerField(default=20),
        ),
    ]
