# Generated by Django 4.0.6 on 2022-07-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_answer_finished_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ball',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(default=20)),
                ('participant_ball', models.IntegerField(default=100)),
                ('ownanswer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.answer')),
                ('participant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.participant')),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.question')),
            ],
        ),
    ]
