# Generated by Django 4.0.6 on 2022-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_answer_ball_participantanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantanswer',
            name='participant_ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
