# Generated by Django 4.0.6 on 2022-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_alter_question_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='technique',
            field=models.IntegerField(choices=[(0, 'Multiple Choices')], default=0, verbose_name='Type of Question'),
        ),
    ]
