# Generated by Django 4.0.6 on 2022-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_question_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passed_tests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
